AWSTemplateFormatVersion: '2010-09-09'
Description: Project hosting static site udacity
Resources:
  ExampleSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl : PublicRead
      BucketName: udacity-test-site-example
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: udacityTestSiteBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref ExampleSiteBucket
                - /*
      Bucket: !Ref ExampleSiteBucket

  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    DependsOn:
    - ExampleSiteBucket
    - BucketPolicy
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Comment: 'Cloudfront Distribution pointing ALB Origin'
        Origins:
          - DomainName: udacity-test-site-example.s3-website-ap-southeast-1.amazonaws.com
            OriginPath: ""
            Id: testUdacitySiteCloudfront
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        Enabled: True
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: testUdacitySiteCloudfront
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
              QueryString: 'true'
              Cookies:
                Forward: none

Outputs:
  WebsiteURL:
    Value: !GetAtt
      - ExampleSiteBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - ExampleSiteBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
  CloudFrontURL:
    Value: !GetAtt
      - CloudFrontDistribution
      - DomainName
    Description: Cloud formation url